name: Code Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

      - name: Build
        run: |
          docker-compose build
    