version: '3.9'
services:
  mongodb:
    image: mongo:4.4.6
    volumes:
      - mongodb_data:/data/db
    restart: always

  rethink:
    image: rethinkdb:latest
    volumes:
      - rethink_data:/data
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    restart: always
  server:
    depends_on:
      - "rethink"
    links:
      - "rethink"
    environment:
      - TZ=Europe/Vienna
      - IN_DOCKER_CONTAINER=1
    build: ./bonsai_server
    ports:
      - 4000:4000
    restart: always

  socket:
    depends_on:
      - "server"
      - "rethink"
    links:
      - "rethink"
    build: ./bonsai_socket
    ports:
      - 9000:9000
    restart: always

  frontend:
    depends_on:
      - "socket"
    build: ./bonsai_frontend/
    ports:
      - 3000:3000
    links:
      - "socket:socket"
      - "server:server"
    environment:
      - TZ=Europe/Vienna
    restart: always

  local_exporter:
    depends_on:
      - "server"
    links:
      - "server:server"
    build: ./bonsai_exporter_base
    restart: always
    deploy:
      replicas: 3


volumes:
  mongodb_data:
  rethink_data:
