version: '3.9'
services:
  rethink:
    image: rethinkdb:latest
    volumes:
      - rethink_data:/data
    restart: always

  server:
    image: ghcr.io/konstfish/bonsai_server
    depends_on:
      - "rethink"
    links:
      - "rethink"
    environment:
      - IN_DOCKER_CONTAINER=1
    ports:
      - 50051:50051
      - 50052:50052
    restart: always

  local_exporter:
    image: ghcr.io/konstfish/bonsai_exporter_base
    depends_on:
      - "server"
    links:
      - "server"
    restart: always

  socket:
    image: ghcr.io/konstfish/bonsai_socket
    depends_on:
      - "server"
      - "rethink"
    links:
      - "rethink"
    environment:
      - IN_DOCKER_CONTAINER=1
    restart: always

  frontend:
    image: ghcr.io/konstfish/bonsai_frontend
    depends_on:
      - "socket"
    ports:
      - 3000:3000
    links:
      - "socket"
    restart: always
volumes:
  rethink_data:
