version: '3.9'
services:
  rethink:
    image: rethinkdb:latest
    volumes:
      - rethink_data:/data
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    restart: always
  server:
    depends_on:
      - "rethink"
    links:
      - "rethink"
    environment:
      - TZ=Europe/London
      - IN_DOCKER_CONTAINER=1
    build: ./bonsai_server
    ports:
      - 50051:50051
      - 50052:50052
    restart: always
  local_exporter:
    depends_on:
      - "server"
    links:
      - "server:server"
    volumes:
      - "./testing/config_container.yaml:/opt/config.yaml"
    build: ./bonsai_exporter_base
    restart: always
    deploy:
      replicas: 3

  docker_exporter_test:
    depends_on:
      - "server"
    links:
      - "server:server"
    environment:
      - PIP_INSTALL=docker,PyYAML
    volumes:
      - "./testing/exporter:/opt/custom_exporters"
      - "./testing/config_docker.yaml:/opt/config.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    build: ./bonsai_exporter_base
    restart: always

  socket:
    depends_on:
      - "server"
      - "rethink"
    links:
      - "rethink"
    environment:
      - TZ=Europe/London
      - IN_DOCKER_CONTAINER=1
    build: ./bonsai_socket
    ports:
      - 9000:9000
    restart: always

  frontend:
    depends_on:
      - "socket"
    build: ./bonsai_frontend/
    ports:
      - 3000:3000
    links:
      - "socket:socket"
      - "server:server"
    environment:
      - TZ=Europe/London
    restart: always

#  rest_interface:
#    depends_on:
#      - "server"
#    links:
#      - "server"
#    environment:
#      - TZ=Europe/London
#      - IN_DOCKER_CONTAINER=1
#    build: ./bonsai_rest_layer
#    ports:
#      - 4000:4000
#    restart: always

#  https-localhost:
#    image: konstfish/https-localhost
#    volumes:
#      - ~/mkcert:/certs
#    ports:
#      - 443:443
#      - 80:80
#    links:
#      - frontend
#    environment:
#      HOST: frontend
#      PORT: 3000
#    restart: always
volumes:
  rethink_data:
