hostname: null
bonsai_server: server:50052
certificate: certs/ca-cert.pem
#bonsai_server: 82.149.123.143:50051
#bonsai_server: server:50051
jobname: demo
rate: 5
labels:
  - docker
exporters:
  BonsaiExporterDOCKER:
    name: DOCKER
    options:
      none: none