---

- name: Get updated files from git repository 
  git: 
    repo: "https://{{ github_user | urlencode }}:{{ github_token | urlencode }}@github.com/konstfish/bonsai.git"
    dest: /home/{{ user_name }}/docker/bonsai-clone

- name: Delete old directory
  file:
    state: absent
    path: /home/{{ user_name }}/docker/bonsai

- name: Copy cloned repo 
  ansible.builtin.copy:
    src: /home/{{ user_name }}/docker/bonsai-clone/
    dest: /home/{{ user_name }}/docker/bonsai/
    remote_src: true

- name: Template docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ user_name }}/docker/bonsai/docker-compose.yml"

- name: Deploy bonsai stack
  docker_compose:
    project_src: /home/{{ user_name }}/docker/bonsai
    state: present
    build: true
    nocache: true
    restarted: true
    recreate: always