apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: bonsai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: init-wait-for-socket
          image: alpine
          command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 socket 9000 && exit 0 || sleep 3; done; exit 1"]
      containers:
        - name: frontend
          image: ghcr.io/konstfish/bonsai_frontend
          resources:
            requests:
              cpu: "20m"
              memory: "128Mi"
            limits:
              cpu: "50m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /nginx_status
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bonsai
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer

