apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethink-deployment
  namespace: bonsai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rethink
  template:
    metadata:
      labels:
        app: rethink
    spec:
      containers:
        - name: rethink
          image: rethinkdb:latest
          ports:
            - containerPort: 28015
            - containerPort: 29015
---
apiVersion: v1
kind: Service
metadata:
  name: rethink
  namespace: bonsai
spec:
  selector:
    app: rethink
  ports:
    - protocol: TCP
      name: rethink
      port: 28015
      targetPort: 28015
    - protocol: TCP
      name: srethink
      port: 29015
      targetPort: 29015