# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bonsai_pb2 as bonsai__pb2


class ServerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/bonsai.Server/RegisterClient',
                request_serializer=bonsai__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=bonsai__pb2.RegistrationConfirmation.FromString,
                )
        self.PushMetrics = channel.unary_unary(
                '/bonsai.Server/PushMetrics',
                request_serializer=bonsai__pb2.MetricsRequest.SerializeToString,
                response_deserializer=bonsai__pb2.MetricsConfirmation.FromString,
                )


class ServerServicer(object):
    """The greeting service definition.
    """

    def RegisterClient(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=bonsai__pb2.RegistrationRequest.FromString,
                    response_serializer=bonsai__pb2.RegistrationConfirmation.SerializeToString,
            ),
            'PushMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMetrics,
                    request_deserializer=bonsai__pb2.MetricsRequest.FromString,
                    response_serializer=bonsai__pb2.MetricsConfirmation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bonsai.Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Server(object):
    """The greeting service definition.
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bonsai.Server/RegisterClient',
            bonsai__pb2.RegistrationRequest.SerializeToString,
            bonsai__pb2.RegistrationConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PushMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bonsai.Server/PushMetrics',
            bonsai__pb2.MetricsRequest.SerializeToString,
            bonsai__pb2.MetricsConfirmation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
