// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: bonsai.proto

package io_grpc_konstfish_bonsai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / registration
// request
type RegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job      string   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Host     string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Key      *string  `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Interval float32  `protobuf:"fixed32,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Labels   []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Scrapers []string `protobuf:"bytes,6,rep,name=scrapers,proto3" json:"scrapers,omitempty"`
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonsai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonsai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_bonsai_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *RegistrationRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegistrationRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *RegistrationRequest) GetInterval() float32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *RegistrationRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegistrationRequest) GetScrapers() []string {
	if x != nil {
		return x.Scrapers
	}
	return nil
}

// confirmation
type RegistrationConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ExporterKey string `protobuf:"bytes,2,opt,name=exporter_key,json=exporterKey,proto3" json:"exporter_key,omitempty"`
}

func (x *RegistrationConfirmation) Reset() {
	*x = RegistrationConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonsai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationConfirmation) ProtoMessage() {}

func (x *RegistrationConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_bonsai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationConfirmation.ProtoReflect.Descriptor instead.
func (*RegistrationConfirmation) Descriptor() ([]byte, []int) {
	return file_bonsai_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationConfirmation) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RegistrationConfirmation) GetExporterKey() string {
	if x != nil {
		return x.ExporterKey
	}
	return ""
}

// / metrics
// metric request
type MetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExporterKey string `protobuf:"bytes,1,opt,name=exporter_key,json=exporterKey,proto3" json:"exporter_key,omitempty"`
	Metrics     []byte `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonsai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonsai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_bonsai_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsRequest) GetExporterKey() string {
	if x != nil {
		return x.ExporterKey
	}
	return ""
}

func (x *MetricsRequest) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// metric confirmation
type MetricsConfirmation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Confirm string `protobuf:"bytes,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
}

func (x *MetricsConfirmation) Reset() {
	*x = MetricsConfirmation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonsai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricsConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsConfirmation) ProtoMessage() {}

func (x *MetricsConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_bonsai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsConfirmation.ProtoReflect.Descriptor instead.
func (*MetricsConfirmation) Descriptor() ([]byte, []int) {
	return file_bonsai_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsConfirmation) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MetricsConfirmation) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

var File_bonsai_proto protoreflect.FileDescriptor

var file_bonsai_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x22, 0xaa, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6a, 0x6f, 0x62,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x63, 0x72, 0x61, 0x70, 0x65, 0x72, 0x73, 0x42, 0x06, 0x0a, 0x04, 0x5f,
	0x6b, 0x65, 0x79, 0x22, 0x51, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x22, 0x4d, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x65, 0x72, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x65, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x73, 0x22, 0x43, 0x0a, 0x13, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x32, 0xa8, 0x01, 0x0a, 0x0d, 0x42,
	0x6f, 0x6e, 0x73, 0x61, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x2e, 0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x6f,
	0x6e, 0x73, 0x61, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12,
	0x44, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x16,
	0x2e, 0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x2e,
	0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x00, 0x42, 0x49, 0x0a, 0x18, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x6b, 0x6f, 0x6e, 0x73, 0x74, 0x66, 0x69, 0x73, 0x68, 0x2e, 0x62, 0x6f, 0x6e, 0x73, 0x61,
	0x69, 0x42, 0x0b, 0x42, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x18, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6b, 0x6f, 0x6e, 0x73, 0x74, 0x66,
	0x69, 0x73, 0x68, 0x2e, 0x62, 0x6f, 0x6e, 0x73, 0x61, 0x69, 0xa2, 0x02, 0x03, 0x48, 0x4c, 0x57,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bonsai_proto_rawDescOnce sync.Once
	file_bonsai_proto_rawDescData = file_bonsai_proto_rawDesc
)

func file_bonsai_proto_rawDescGZIP() []byte {
	file_bonsai_proto_rawDescOnce.Do(func() {
		file_bonsai_proto_rawDescData = protoimpl.X.CompressGZIP(file_bonsai_proto_rawDescData)
	})
	return file_bonsai_proto_rawDescData
}

var file_bonsai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bonsai_proto_goTypes = []interface{}{
	(*RegistrationRequest)(nil),      // 0: bonsai.RegistrationRequest
	(*RegistrationConfirmation)(nil), // 1: bonsai.RegistrationConfirmation
	(*MetricsRequest)(nil),           // 2: bonsai.MetricsRequest
	(*MetricsConfirmation)(nil),      // 3: bonsai.MetricsConfirmation
}
var file_bonsai_proto_depIdxs = []int32{
	0, // 0: bonsai.BonsaiService.RegisterClient:input_type -> bonsai.RegistrationRequest
	2, // 1: bonsai.BonsaiService.PushMetrics:input_type -> bonsai.MetricsRequest
	1, // 2: bonsai.BonsaiService.RegisterClient:output_type -> bonsai.RegistrationConfirmation
	3, // 3: bonsai.BonsaiService.PushMetrics:output_type -> bonsai.MetricsConfirmation
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bonsai_proto_init() }
func file_bonsai_proto_init() {
	if File_bonsai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bonsai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonsai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonsai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonsai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricsConfirmation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_bonsai_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bonsai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bonsai_proto_goTypes,
		DependencyIndexes: file_bonsai_proto_depIdxs,
		MessageInfos:      file_bonsai_proto_msgTypes,
	}.Build()
	File_bonsai_proto = out.File
	file_bonsai_proto_rawDesc = nil
	file_bonsai_proto_goTypes = nil
	file_bonsai_proto_depIdxs = nil
}
