hostname: None
#bonsai_server: 127.0.0.1:50051
#bonsai_server: 82.149.123.143:50051
bonsai_server: server:50051
jobname: demo
rate: 1
labels:
 - asdf
 - test
 - python
exporters:
  BonsaiExporterCPU:
    name: CPU
    labels:
      service: test
    options:
      "individual_cores": True
      "core_count": True
      "core_count_logical": True
  BonsaiExporterMEM:
    name: MEM
    options:
      "include_swap": False
      "detailed": True
  BonsaiExporterNET:
    options:
      "interfaces": ["ensdfs0"]
  BonsaiExporterDISK:
    options:
      "disks": ['/']
      "detailed": True
