hostname: null
bonsai_server: server:50051
jobname: demo
rate: 1
labels:
  - default
exporters:
  BonsaiExporterCPU:
    name: CPU
    options:
      "individual_cores": True
      "core_count": True
      "core_count_logical": True
  BonsaiExporterMEM:
    name: MEM
    options:
      "include_swap": False
      "detailed": True
  BonsaiExporterNET:
    name: NET
    options:
      "interfaces": ["en0"]
