hostname: None
bonsai_server: server:50052
certificate: certs/ca-cert.pem
#bonsai_server: 82.149.123.143:50051
#bonsai_server: server:50051
jobname: demo
rate: 1
labels:
  - python
  - test
  - asf
exporters:
  BonsaiExporterCPU:
    name: CPU
    options:
      "individual_cores": True
      "core_count": True
      "core_count_logical": True
  BonsaiExporterMEM:
    name: MEM
    options:
      "include_swap": False
      "detailed": True
  BonsaiExporterNET:
    name: NET
    options:
      "interfaces": ["ensdfs0"]
  BonsaiExporterDISK:
    name: DISK
    options:
      "disks": ['/']
      "detailed": True
