name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Build
        run: |
          docker-compose build
    