# Publish docker containers to github registry
name: Publish

on:
  # Trigger the workflow on a new release
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build bonsai_socket
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_socket
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/bonsai_socket:${{ github.event.release.tag_name }}
            ghcr.io/konstfish/bonsai_socket:latest

      - name: Build bonsai_server
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/bonsai_server:${{ github.event.release.tag_name }}
            ghcr.io/konstfish/bonsai_server:latest

      - name: Build bonsai_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/bonsai_frontend:${{ github.event.release.tag_name }}
            ghcr.io/konstfish/bonsai_frontend:latest

      - name: Build bonsai_exporter_base 
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_exporter_base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/konstfish/bonsai_exporter_base:${{ github.event.release.tag_name }}
            ghcr.io/konstfish/bonsai_exporter_base:latest
