# Publish docker containers to github registry
name: Publish

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build bonsai_server
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_server
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: bonsai/bonsai_server:latest

      - name: Build bonsai_socket
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_socket
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: bonsai/bonsai_socket:latest

      - name: Build bonsai_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_frontend
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: bonsai/bonsai_frontend:latest

      - name: Build bonsai_exporter_base 
        uses: docker/build-push-action@v2
        with:
          context: ./bonsai_exporter_base
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: bonsai/bonsai_exporter_base:latest